name: vendomesdelivery
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  intl: ^0.17.0
  universal_platform: ^1.0.0+1
  universal_html: ^2.0.8
  firebase:
  cloud_firestore:
  firebase_core:
  firebase_auth:
  flutter_launcher_icons: ^0.9.2
  collection: ^1.15.0
  firebase_storage:
  image_picker: ^0.8.4+11
  supercharged: ^2.1.1
  file_picker: ^4.5.1
  flutter_rating_bar: ^4.0.0
  flutter_native_splash: ^2.1.6
  lazy_load_scrollview: 1.3.0
  flutter_number_picker: ^1.0.4

  google_maps_flutter: ^2.1.3
  flutter_polyline_points: ^1.0.0
  uuid: ^3.0.6
  flutterfire_ui:


  location: ^4.4.0
  dio: ^4.0.6
  google_maps_flutter_web: ^0.3.2+1
  permission_handler: ^9.2.0
  flutter_google_places: ^0.3.0
  geocoding: ^2.0.4
  geolocator: ^8.2.1

  flutter_compass: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  image: assets/images/splash.png
  color: "#000000"
  web: false
  android: true
  ios: true

  android_12:
    image: assets/images/splash.png
    android: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/styles/
    - assets/images/
    - assets/images/appicon/
    - assets/images/mapsicons/
    - assets/images/promo/
    - assets/images/headerimages/
    - assets/images/premiumbrands/
    - assets/images/homepageicons/
    - assets/images/restaurentimages/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appicon/appicon.png"
  adaptive_icon_background: "#000000"

fonts:
  - family: crimson
    fonts:
      - assets: assets/fonts/crimson.bold.ttf
      - assets: assets/fonts/crimson.italic.ttf
      - assets: assets/fonts/crimson.roman.ttf
      - assets: assets/fonts/crimson.semibold.ttf
      - assets: assets/fonts/crimson.semibolditalic.ttf
